In [ ]:
#%pip install tensorflow

In [6]:
# importing packages

import pandas as pd
import numpy as no

import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf 
from tensorflow import keras #keras gives convinent api to use

#Scaling the data
from sklearn.preprocessing import StandardScaler


%matplotlib inline

import warnings
warnings.filterwarnings('ignore')



In [ ]:
#%pip install torch

In [29]:
data = pd.read_csv('student_data.csv')
data.head()

admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4

In [30]:
data.shape

(400, 4)

In [42]:
y = data.iloc[:, [3]]
X = data.drop('rank', axis=1)

In [43]:
X.shape

(400, 3)

In [44]:
y.shape

(400, 1)

In [45]:
from sklearn.model_selection import train_test_split
X_training_data, X_test_data, y_train_data, y_test_data = train_test_split(X, y , test_size=0.3, random_state=25)

In [47]:
X_training_data.shape

(280, 3)

In [48]:
y_train_data.shape

(280, 1)

In [51]:
#Preprocessing: Scale the data so that both gre and gpa are in same scaling range
X_train_scaled = X_training_data.copy()
X_train_scaled['gre'] = X_train_scaled['gre']/100

X_test_scaled = X_test_data.copy()
X_test_scaled['gre'] = X_test_scaled['gre']/100

In [66]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(3,), activation= 'sigmoid', kernel_initializer= 'ones', bias_initializer = 'zeros')
])

model.compile(optimizer='adam',
loss='binary_crossentropy',
metrics=['accuracy']) 

model.fit(X_train_scaled, y_train_data, epochs=30)

Epoch 1/30
9/9 [==============================] - 0s 1000us/step - loss: -13.7230 - accuracy: 0.1500
Epoch 2/30
9/9 [==============================] - 0s 1ms/step - loss: -13.8580 - accuracy: 0.1500
Epoch 3/30
9/9 [==============================] - 0s 1ms/step - loss: -13.9929 - accuracy: 0.1500
Epoch 4/30
9/9 [==============================] - 0s 1ms/step - loss: -14.1287 - accuracy: 0.1500
Epoch 5/30
9/9 [==============================] - 0s 1ms/step - loss: -14.2640 - accuracy: 0.1500
Epoch 6/30
9/9 [==============================] - 0s 811us/step - loss: -14.3981 - accuracy: 0.1500
Epoch 7/30
9/9 [==============================] - 0s 1000us/step - loss: -14.5324 - accuracy: 0.1500
Epoch 8/30
9/9 [==============================] - 0s 1ms/step - loss: -14.6683 - accuracy: 0.1500
Epoch 9/30
9/9 [==============================] - 0s 1ms/step - loss: -14.8029 - accuracy: 0.1500
Epoch 10/30
9/9 [==============================] - 0s 1ms/step - loss: -14.9384 - accuracy: 0.1500
Epoch 11/30

In [67]:
model.evaluate(X_test_scaled, y_test_data) #gave 15 percent accuracy

4/4 [==============================] - 0s 3ms/step - loss: -19.0414 - accuracy: 0.1583


[-19.04141616821289, 0.15833333134651184]

In [68]:
model.predict(X_test_scaled)

array([[0.9999832 ],
       [0.99999964],
       [0.99998593],
       [0.9999925 ],
       [0.9999948 ],
       [1.        ],
       [0.99997425],
       [1.        ],
       [0.99997485],
       [0.9999976 ],
       [0.99999356],
       [0.99999   ],
       [1.        ],
       [0.9999764 ],
       [0.99998736],
       [0.9999994 ],
       [0.9999973 ],
       [0.9999974 ],
       [0.9999993 ],
       [0.9999961 ],
       [0.9999943 ],
       [0.99992025],
       [0.9999943 ],
       [0.9999981 ],
       [0.9999582 ],
       [1.        ],
       [0.9999981 ],
       [0.9999989 ],
       [0.99999756],
       [0.9999955 ],
       [1.        ],
       [0.9999959 ],
       [0.99999607],
       [0.9999994 ],
       [0.99994814],
       [0.99999744],
       [0.9999962 ],
       [0.99999815],
       [0.99999964],
       [0.9999988 ],
       [0.9999937 ],
       [0.99999064],
       [0.99999034],
       [0.9999974 ],
       [0.99999547],
       [0.9999671 ],
       [0.9999889 ],
       [0.999

In [69]:
y_test_data

rank
121     2
162     2
338     1
375     4
262     3
..    ...
140     2
204     1
359     3
312     3
199     4

[120 rows x 1 columns]

In [70]:
#Now get the value of weights and bias from the model: coef , intercept is known w1, w2, bias
coef , intercept = model.get_weights()

In [71]:
coef, intercept

##this means that w1 = 1.2579206 , w2 = 1.2680393, w3= 1.2681689 bias = 0.26820916

(array([[1.2569085],
        [1.2680928],
        [1.2682104]], dtype=float32),
 array([0.26827973], dtype=float32))

In [72]:
model.predict(X_test_scaled)

array([[0.9999832 ],
       [0.99999964],
       [0.99998593],
       [0.9999925 ],
       [0.9999948 ],
       [1.        ],
       [0.99997425],
       [1.        ],
       [0.99997485],
       [0.9999976 ],
       [0.99999356],
       [0.99999   ],
       [1.        ],
       [0.9999764 ],
       [0.99998736],
       [0.9999994 ],
       [0.9999973 ],
       [0.9999974 ],
       [0.9999993 ],
       [0.9999961 ],
       [0.9999943 ],
       [0.99992025],
       [0.9999943 ],
       [0.9999981 ],
       [0.9999582 ],
       [1.        ],
       [0.9999981 ],
       [0.9999989 ],
       [0.99999756],
       [0.9999955 ],
       [1.        ],
       [0.9999959 ],
       [0.99999607],
       [0.9999994 ],
       [0.99994814],
       [0.99999744],
       [0.9999962 ],
       [0.99999815],
       [0.99999964],
       [0.9999988 ],
       [0.9999937 ],
       [0.99999064],
       [0.99999034],
       [0.9999974 ],
       [0.99999547],
       [0.9999671 ],
       [0.9999889 ],
       [0.999